# This is a basic workflow to help you get started with Actions

name: Notion Exporter

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: igor-kupczynski/notion-exporter@ecd2eebe438a69fe8a9bbfd4e4ac4ec4d9e05007
     # Comma-separated list of page to export the data from
    pages: 
    # Github token to use to commit to the repo
    github-token: 
    # Value of the token_v2 cookie
    notion-token: 
    # Directory under your repo to sync the data to; note the existing files will be deleted
    output-dir: 
    # Override the branch to use, defaults to the branch you run your workflow on
    force-branch: # optional
          
